config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'movies/index'
  root to: "movies#index"
  resources :movies do
    collection do
      get 'search'
    end
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :new]
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :movie
  belongs_to :user

  # アクティブハッシュ
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :genre

  validates :text, presence: true

  validates :genre_id, numericality: { other_than: 1 }
end

app/models/genre.rb
class Genre < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'good' },
    { id: 3, name: 'bad' },
    { id: 4, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :comments

  end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :movie
  belongs_to :user

  validates_uniqueness_of :movie_id, scope: :user_id
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :tag_maps,dependent: :destroy
  has_many :tags, through: :tag_maps
  has_many :likes,dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many :comments,dependent: :destroy
  has_many :tag_maped_tags, through: :tag_maps, source: :tag

  validates :movie_name, presence: true

  # タグ保存時コード
  def actor_tags_save(tag_list)
    if self.tags != nil
      movie_tags_records = TagMap.where(movie_id: self.id)
      movie_tags_records.destroy_all
    end
    tag_list.each do |tag|
      inspected_tag = Tag.where(actor_tag: tag).first_or_create
      self.tags << inspected_tag
    end
  end
  def genre_tags_save(tag_list)
    if self.tags != nil
      movie_tags_records = TagMap.where(movie_id: self.id)
      movie_tags_records.destroy_all
    end
    tag_list.each do |tag|
      inspected_tag = Tag.where(genre_tag: tag).first_or_create
      self.tags << inspected_tag
    end
  end
  def distribution_tags_save(tag_list)
    if self.tags != nil
      movie_tags_records = TagMap.where(movie_id: self.id)
      movie_tags_records.destroy_all
    end
    tag_list.each do |tag|
      inspected_tag = Tag.where(distribution_site_tag: tag).first_or_create
      self.tags << inspected_tag
    end
  end
  def other_tags_save(tag_list)
    if self.tags != nil
      movie_tags_records = TagMap.where(movie_id: self.id)
      movie_tags_records.destroy_all
    end
    tag_list.each do |tag|
      inspected_tag = Tag.where(other_tag: tag).first_or_create
      self.tags << inspected_tag
    end
  end


  # タグ検索時scope
  scope :having_all_tags_of, ->(*tag_ids) {
    where(id: TagMap.select(:movie_id)
      .where(tag_id: tag_ids)
      .group( :movie_id )
      .having("COUNT(DISTINCT tag_maps.tag_id) = ?", (tag_ids.size-4))
    )
  }
  

  private

   def self.ransackable_scopes(auth_object = nil)
     %i(having_all_tags_of)
   end  
   
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tag_maps
  has_many :movies, through: :tag_maps
  has_many :tag_maped_movies, through: :tag_maps, source: :movie
end

app/models/tag_map.rb
class TagMap < ApplicationRecord
  belongs_to :movie
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true

  has_many :likes, dependent: :destroy
  has_many :liked_movies, through: :likes, source: :movie
  has_many :comments

  def already_liked?(movie)
    self.likes.exists?(movie_id: movie.id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @movie = Movie.find(params[:movie_id])
    @comment=Comment.create(comment_params)
    comment=@comment
    render json:{ comment: comment }
  end

  private
  def comment_params
    params.require(:comment).permit(:text, :genre_id ).merge(user_id: current_user.id, movie_id: params[:movie_id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.create(movie_id: params[:movie_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @like = Like.find_by(movie_id: params[:movie_id], user_id: current_user.id)
    @like.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :search_movie, only: [:index, :search]
  before_action :authenticate_user!, except: [:index, :search]
  before_action :move_to_root,only: [:new, :create, :destroy]
  require 'themoviedb-api'
  Tmdb::Api.key(ENV["TMDB_API_KEY"])
  Tmdb::Api.language("ja")


  def index
    @movies = Movie.all
    @actor_tags=Tag.where.not(actor_tag: nil)
    @genre_tags=Tag.where.not(genre_tag: nil)
    @distribution_tags=Tag.where.not(distribution_site_tag: nil)
    @other_tags=Tag.where.not(other_tag: nil)
    @ranking=Movie.find(Like.group(:movie_id).order('count(movie_id) desc').limit(5).pluck(:movie_id))
    @add_movie=Movie.order('created_at desc').limit(5)
  end

  def new
    @movie = Movie.new
  end
  def create
    @movie = Movie.new(movie_params)
    actor_tag_list = params[:movie][:actor_tag].split(",")
    genre_tag_list = params[:movie][:genre_tag].split(",")
    distribution_tag_list = params[:movie][:distribution_site_tag].split(",")
    other_tag_list = params[:movie][:other_tag].split(",")
    @movie.actor_tags_save(actor_tag_list)
    @movie.genre_tags_save(genre_tag_list)
    @movie.distribution_tags_save(distribution_tag_list)
    @movie.other_tags_save(other_tag_list)
    if @movie.valid?
      @movie.save    
      return redirect_to root_path
    else
      render "new"
    end
  end

  def search
    @results=@p.result
  end

  def show
    @movie = Movie.find(params[:id])
    @like = Like.new
    @comment = Comment.new
    @good_comments = @movie.comments.where(genre_id: 2).includes(:user)
    @bad_comments = @movie.comments.where(genre_id: 3).includes(:user)
    @other_comments = @movie.comments.where(genre_id: 4).includes(:user)
    gon.movie=@movie

    gon.user=current_user.nickname
  end
  def destroy
    movie = Movie.find(params[:id])
    movie.destroy
    redirect_to root_path
  end



  private

  def search_movie
    @p = Movie.ransack(params[:q])
  end


  def movie_params
    params.require(:movie).permit(:movie_name)
  end

  def move_to_root
    unless user_signed_in? && current_user.admin?
      redirect_to root_path
    end
  end
  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]
  before_action :move_to_root,only: [:show]
  def show
    @nickname = current_user.nickname
    @user = User.find(params[:id])
    
  end
end

private

def move_to_root
  unless User.find(params[:id]).id == current_user.id
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieNow</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= include_gon %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/index.html.erb
<div class="header-image">
  <%= render "shared/header" %>
</div>

<main class="index-main">
  <div>
    <h2 class="index-main-string">まさに今観たい映画に出会える</h2>
  </div>
  <div class="add-movies">
    <h1 class="add-movie-title"><span class="add-movie-title-in">新規追加作品 ＞</span></h1>
    <div class="add-movie-block">
      <% @add_movie.each do |movie| %>
        <div class="add-movie-lists">         
          <% movieinfo = JSON.parse((Tmdb::Search.movie(movie.movie_name)).to_json) %>
          <% if movieinfo['table']['results'].present? %>
            <p class="index-img-box"><%= image_tag 'https://image.tmdb.org/t/p/w154' + movieinfo['table']['results'][0]['table']['poster_path'],class: "card-img" %></p>
          <% else %>
            <div class="no-image">画像はありません</div>
          <%end%>
          <%= link_to movie.movie_name,  movie_path(movie.id) %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="ranking">
    <h1 class="ranking-title"><span class="ranking-title-in">ランキング ＞</span></h1>
    <div class="ranking-block">
      <% i=0 %>
      <% @ranking.each do |movie| %>
        <% i +=1 %>
        <div class="ranking-lists">
          <span class="ranking-num"><%= "#{i}位" %></span>
          <% movieinfo = JSON.parse((Tmdb::Search.movie(movie.movie_name)).to_json) %>
          <% if movieinfo['table']['results'].present? %>
            <p class="index-img-box"><%= image_tag 'https://image.tmdb.org/t/p/w154' + movieinfo['table']['results'][0]['table']['poster_path'],class: "card-img" %></p>
          <% else %>
            <div class="no-image"><span>画像はありません</span></div> 
          <%end%>
          <%= link_to movie.movie_name,  movie_path(movie.id) %>
          
        </div>
      <% end %>
    </div>
  </div>

  <div class="movie-search">
    <h1 class="index-search-title">
      <span class="index-search-title-in">映画検索 ＞</span>
    </h1>
    <div class="tag-form-main">
      <p class="search-explanation">＊１つ以上のタグを選択し、検索ボタンを押して下さい(全てのタグが含まれる映画が表示されます)</p>
      <%= search_form_for @p, url: search_movies_path, id: "tag_form" do |f| %>

        <div class="tag_list">
          <div class="tag-block">
          <p class="tag-title">■出演者</p>
          <div class="tags"><%= f.collection_check_boxes :having_all_tags_of, @actor_tags, :id, :actor_tag %></div>
          </div>
          <div class="tag-block">
          <p class="tag-title">■ジャンル</p>
          <div class="tags"><%= f.collection_check_boxes :having_all_tags_of, @genre_tags, :id, :genre_tag %></div>
          </div>
          <div class="tag-block">
          <p class="tag-title">■配信サイト</p>
          <div class="tags"><%= f.collection_check_boxes :having_all_tags_of, @distribution_tags, :id, :distribution_site_tag %></div>
          </div>
          <div class="tag-block">
          <p class="tag-title">■その他</p>
          <div class="tags"class="tags"><%= f.collection_check_boxes :having_all_tags_of, @other_tags, :id, :other_tag %></div>
          </div>
        </div>
        <div class="search-btn-box"><%= f.submit '検索開始', class: "search-btn" %></div>
      <% end %>
    <div>
  </div>
</main>

<div>
  <%= render "shared/footer" %>
</div>

app/views/movies/new.html.erb
<div class="second-header-block">
  <%= render "shared/second-header" %>
</div>

<div class="post-movie">
  <%= form_with model: @movie, url: movies_path, class:'post-main', local: true do |f| %>
    <div class='form-wrap-add'>
      <div class='form-header'>
        <h1 class='form-header-text'>
          追加作品情報入力
        </h1>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <%= f.label :movie_name,  "映画名", class:"form-text" %>
        </div>
        <%= f.text_field :movie_name, class:"input-default" %>
      </div>
        
      <div class="form-group">
        <div class='form-text-wrap'>
          <%= f.label :actor_tag, "出演者タグ", class:"form-text" %>
        </div>
        <%= f.text_area :actor_tag, placeholder:"例)#トトロ,#さつき,#めい", class:"input-default-add" %>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <%= f.label :genre_tag, "ジャンルタグ", class:"form-text" %>
        </div>
        <%= f.text_area :genre_tag, placeholder:"例)#アニメ", class:"input-default-add" %>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <%= f.label :distribution_site_tag, "配信サイトタグ", class:"form-text" %>
        </div>
        <%= f.text_area :distribution_site_tag, placeholder:"例)#Netflix", class:"input-default-add" %>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <%= f.label :other_tag, "その他タグ", class:"form-text" %>
        </div>
        <%= f.text_area :other_tag, placeholder:"例)#ジブリ,#宮崎駿,#家族,#子供", class:"input-default-add" %>
      </div>
      <div class="warning">
        <p>＊タグ名の先頭に「#」を付けて下さい。また、同じ枠内に複数のタグをつける際にはタグ間を「,」で区切ってください。</p>
      </div>
      <div class="register-btn">
        <%= f.submit "作品追加", class: "register-red-btn" %>
      </div>
    </div>
  <% end %>
</div>

<div>
  <%= render "shared/second-footer" %>
</div>

app/views/movies/search.html.erb
<div class="second-header-block">
  <%= render "shared/second-header" %>
</div>
<div class="search-room">
  <div class="search-title-block">
    <h1 class="search-title">検索結果</h1>
  </div>
  <div class="search-result">
    <div class="search-result-movies">
      <% unless @results.blank? %>
      
        <% @results.each do |result| %>
          <div class="search-each-result">
            <% movieinfo = JSON.parse((Tmdb::Search.movie(result.movie_name)).to_json) %>
            <% if movieinfo['table']['results'].present? %>
              <p class="search-movie-img-box"><%= image_tag 'https://image.tmdb.org/t/p/w500' + movieinfo['table']['results'][0]['table']['poster_path'],class: "search-img" %></p>
            <% elsif %>
              <div class="no-search-img"><p>画像はありません</p></div>  
            <%end%>
            <%= link_to result.movie_name,  movie_path(result.id), class: "search-movie-title" %>
          </div>
        <% end %>
     
      <% else %>
        <div class="no-result"><p>該当する作品はありません</P></div>
      <% end %>
    </div>
  </div>
</div>
<div>
  <%= render "shared/second-footer" %>
</div>

app/views/movies/show.html.erb
<div class="second-header-block">
  <%= render "shared/second-header" %>
</div>
<div class="movie-show">
  <div class="show-top">
    <div class="show-top-left">
      <% movieinfo = JSON.parse((Tmdb::Search.movie( @movie.movie_name)).to_json) %>
      <% if movieinfo['table']['results'].present? %>
        <div><%= image_tag 'https://image.tmdb.org/t/p/w500' + movieinfo['table']['results'][0]['table']['poster_path'],class: "card-img-show" %></div>
      <% elsif %>
        <div class="no-card-img-show"><p>画像はありません</p></div> 
      <%end%>
    </div>
    <div class="show-top-right">
      <div class="show-movie-name">
        <%= @movie.movie_name %>
      </div>
      <div class="movie-explanation">
        <p class="explanation-title">＜ 概要 ＞</p>
        <% if movieinfo['table']['results'].present? %>
          <%= movieinfo['table']['results'][0]['table']['overview'] %>
        <%elsif%>
          <div class="no-movie-explanation"><p>概要はありません</p></div>
        <%end%>
      </div>
      <div class="show-tags">
        <div class="show-actor-tag">
          <div class="show-tag-title">■出演者：</div>
          <div  class="show-tag">
            <%@movie.tag_maped_tags.each do |tag| %>
              <span><%= tag.actor_tag %></span>
            <% end %>
          </div>
        </div>
        <div class="show-genre-tag">
          <div class="show-tag-title">■ジャンル：</div>
          <div  class="show-tag">
            <%@movie.tag_maped_tags.each do |tag| %>
              <span><%= tag.genre_tag %></span>
            <% end %>
          </div>
        </div>
        <div class="show-distribution-tag">
          <div class="show-tag-title">■配信サイト：</div>
          <div  class="show-tag">
            <%@movie.tag_maped_tags.each do |tag| %>
              <span><%= tag.distribution_site_tag %></span>
            <% end %>
          </div>
        </div>
        <div class="show-other-tag">
          <div class="show-tag-title">■その他：</div>
          <div  class="show-tag">
            <%@movie.tag_maped_tags.each do |tag| %>
              <span><%= tag.other_tag %></span>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="show-middle">

    <div class="show-middle-left">
      <% if user_signed_in? && current_user.admin? %>
        <div class="movie-delete">
          <%= button_to '映画の削除', movie_path(@movie.id), method: :delete, class: "movie-delete-btn" %>
        </div>
      <% end %>
    </div>
    <div class="shoe-middle-right">
      <% if current_user.already_liked?(@movie) %>
        <span><%= button_to 'いいね👍', movie_like_path(@movie), method: :delete, class: "good-btn" %></span>
      <% else %>
        <span><%= button_to 'いいね👍', movie_likes_path(@movie), class:"no-good-btn" %></span>
      <% end %>
      <div class="good-count">いいね:<%= @movie.likes.count %>件</div>
    </div>

  </div>  
  <div>
    <h2 class="comment-title">★コメントしよう！</h2>
    <div class="all-comments">
      <div class="comment-block-good" id="comment-block-good">
        <h4 class="comment-block-name">＜goodコメント一覧＞</h4>
        <% @good_comments.each do |comment| %>
          <p class="name-comment">
            <%= comment.user.nickname %>：
            <%= comment.text %>
          </p>
        <% end %>
      </div>
      <div class="comment-block-bad" id="comment-block-bad">
        <h4 class="comment-block-name">＜badコメント一覧＞</h4>
        <% @bad_comments.each do |comment| %>
          <p class="name-comment"> 
            <%= comment.user.nickname %>：
            <%= comment.text %>
          </p>
        <% end %>
      </div>
      <div class="comment-block-other" id="comment-block-other">
        <h4 class="comment-block-name">＜その他コメント一覧＞</h4>
        <% @other_comments.each do |comment| %>
          <p class="name-comment"> 
            <%= comment.user.nickname %>：
            <%= comment.text %>
          </p>
        <% end %>
      </div>
      <div class="comment-block-form">
        <h4 class="comment-block-name">＜投稿フォーム＞</h4>
        <% if user_signed_in? %>
          <%= form_with(model: [@movie, @comment], local: true, id: "comment-form") do |form| %>
            <div class="comment-in-box">
              <%= form.text_area :text, placeholder: "コメントする", rows: "4",class: "comment-in", id: "comment-in" %>
            </div>
            <div class="comment-form-bottom">
              <%= form.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"genre-select", id: "genre-select"}) %>
              <%= form.submit "投稿", class:"comment-btn", id: "comment-submit" %>
            </div>
            <p class="comment-caution">＊「good」、「bad」、「その他」から１つ選択して下さい</p>
          <% end %>
        <% else %>
          <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div>
  <%= render "shared/second-footer" %>
</div>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<div class="main-footer-block">
  <% if user_signed_in? && current_user.admin? %>
    <div class="admin-btn-box"><%= link_to '管理者画面', new_movie_path, class: "admin-link" %></div>
  <% end %>
</div>

app/views/shared/_header.html.erb
<header class="main-header">
  <div class="header-left">
    <div class="fas fa-film fa-5x"></div>
    <div class="rogo-string">
      <span class="rogo">movie</span><br>
      <span class="rogo-bottom">now</span>
    </div>

  </div>
  <div class="header-right">
    <ul class='right-lists'>
      <% if user_signed_in? %>
        <li><%= link_to current_user.nickname, user_path(current_user.id), class: "user-nickname" %></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
      <% else %>
        <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
        <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
      <% end %>
    </ul>
  </div>
</header>

app/views/shared/_second-footer.html.erb
<div class="second-footer-block">
   <p class="show-root-path"><%= link_to 'トップページ', root_path,class:'second-header-root' %></p>
</div>

app/views/shared/_second-header.html.erb
<header class="second-header">
  <div class="header-left">
    <div class="fas fa-film fa-5x"></div>
    <div class="rogo-string">
      <span class="rogo">movie</span><br>
      <span class="rogo-bottom">now</span>
    </div>
  </div>
  <div class="header-right">
    
  </div>
</header>

app/views/users/show.html.erb
<div class="second-header-block">
  <%= render "shared/second-header" %>
</div>

<div class="user-myroom">
  <h1 class="user-myroom-title"><%=  @nickname %>さんの映画コレクション</h1>
  <h3 class="myroom-good-title">＜「いいね」している投稿＞</h3>
  <div class="myroom-good-lists">
    <% @user.liked_movies.each do |movie| %>
      <div class="myroom-each-movie">
        <% movieinfo = JSON.parse((Tmdb::Search.movie( movie.movie_name )).to_json) %>
        <% if movieinfo['table']['results'].present? %>
          <p><%= image_tag 'https://image.tmdb.org/t/p/w500' + movieinfo['table']['results'][0]['table']['poster_path'],class: "myroom-img" %></p>
        <%elsif%>
          <div class="no-myroom-img"><p>画像はありません</p></div>
        <%end%>
        <p class="myroom-movie-title"><%= link_to movie.movie_name,  movie_path(movie.id) %></p> 
      </div> 
   <% end %>
  </div>
</div>

<div>
  <%= render "shared/second-footer" %>
</div>